### ISSUE TITLE
Different types of blacklists

### ISSUE THREAD

**Issue by tenten8401** [DoubleDoorDevelopment/ItemBlacklist#11]
We need different types of item blacklists, sort of like ItemRestrict (plugin)... Like ownership, placing, etc.

**Comment by dries007** [comment]
Well, the idea is that you can unpack the items to craft with. So for example, you can ban TNT but still allow any recipes that use it. As soon as you try to add granularity, the mob becomes a lot more complex and bypasses will creep in.

With Forge it is also (practically) impossible to prevent specific inventory manipulations & crafting.

Do you have any particular functionality you need/want, and why?

**Comment by Claycorp** [comment]
* Stopping someone from owning something would also stop them from placing it?
 * Stopping someone from placing something stops someone from owning it? (It's a useless item thus who cares if they have it. Nothing can use it.)

What else would you need to stop people from doing? It already works per DIM and you can set it up to work within a pack. That covers all the options the plugin you talk about has.

Also I don't recommend using this mod unless you can't edit whatever you want to remove via mod configs. It's always better to rely on the mod itself rather than an extra mod. Plus as you need this serverside and clientside if you modify an existing pack everyone that joins will need to install it.

**Comment by tenten8401** [comment]
Thing is, with some mods, like block placers, players can put their items in there and place em down, as if a chunk loader was banned.

**Comment by Claycorp** [comment]
That doesn't work with this mod. This isn't a conventional item/block blacklister.

**Comment by dries007** [comment]
Any blockplacers in 1.9+ should use (fake) players and use the forge hook when doing any world interactions, if they are not, they are doing weird things and should probably be informed of the inconsistency.

**Comment by tenten8401** [comment]
Ah. I'll give it a shot on my public server
