### ISSUE TITLE
Feature Suggestion: Unlock Leveling System

### ISSUE THREAD

**Issue by K4N0** [DoubleDoorDevelopment/ItemBlacklist#4]
It would be really cool for players to be able to unlock items by paying $$ or XP.
You can configure how much money or xp is required to to have access to such items / blocks
You can set it up so that nothing is restricted and modpack creators can set the amounts per blocks or items. It would turn into a leveling system so that players can't just have other players give them all the stuff and ruin their experience.

**Comment by Claycorp** [comment]
The mod dosn't allow this at all.
Banned items are based off dimension only. That means it's banned for everyone or nobody.

**Comment by K4N0** [comment]
ok np, hey i made a mod showcase but i want you to check it out first. let me know if i missed anything before i upload it.

**Comment by K4N0** [comment]
.

**Comment by Claycorp** [comment]
Sorry bout the late reply. (I saw the message a while ago and just got to it)

First of I want to say that you doing great! That was a very nice spotlight of the mod. Though i do have a few tips for ya. (If you want to publish it that is fine else you can try again with these tips! Either way is fine by me.)
1. Make sure that your sounds are at the correct levels. Background sounds shouldn't overpower main voices/actions/sounds. At times I had a hard time understanding what you said over the wubs :P
2. When showing off features make sure that you show them! Having your friend with you is great but when a feature you are talking about can't be seen people are possibly going to stray away from looking at more content or are not as likely to share it.
3. When you talked about some features you seemed to get a bit confused at what you were saying sometimes. I've been there done that. I could say script it out so everything is included but that's more work and not as natural in my opinion. Though I would for sure make some sort of document with bullet points as like an overview for yourself as you record so that way you don't get lost/repeat info multiple times/whatever!

Otherwise it looks great! You went over all the information in detail. Good luck with your future content!

**Comment by K4N0** [comment]
Thanks for the advice. I really appreciate it. My videos will continue to get better. 
I was debating turning down the background sound. I think i will. I did.
https://www.youtube.com/watch?v=Gnykbv-hvHs&feature=youtu.be

I didn't show off actually typing in the commands cause i didn't really use them all.
I didn't script it cause i end up sounding like a robot, but yes i do need some sort of bullet points.
I tried to do that with the wall i setup but those things didn't really help much more than a sign did.

**Comment by Claycorp** [comment]
Sounds much better!

About the command part...
Since it was in information related command I personally would like to see it so you can talk about the format that is seen. Think like how you have the text on the wall shows it. Anyway i'm going to close this issue. Good luck with your youtube! 

Also thanks for the spotlight! Ill add it to curseforge real quick.
If you have anymore questions/comments/ideas feel free to open a new issue.
