### ISSUE TITLE
Item Blacklist minor bug prevents World Primer using /unpack, even when unpack4all enabled

### ISSUE THREAD

**Issue by TyrusJames** [DoubleDoorDevelopment/ItemBlacklist#40]
https://github.com/DoubleDoorDevelopment/ItemBlacklist/blob/cf5b1f85ac6a3b9bf0fdafa7c91b261fb390a434/src/main/java/net/doubledoordev/itemblacklist/util/CommandUnpack.java#L35

sender instanceof EntityPlayer
Should be
sender.getCommandSenderEntity() instanceof EntityPlayer

To allow /execute commands that have /unpack in them. So they work via World Primer and most likely for command blocks also - It looks like that was someone's issue previously.

**Comment by Claycorp** [comment]
As mentioned in #41 this mod is old and functionally done for 1.12 as I have moved on from 1.12. I'm counting this as a "feature" as I don't recall why it would have been made like this otherwise and I don't want to change something that could cause issues later.

I provided some options to you on curseforge as a way to get around it that would be safer than changing how the command works.
